### PR TITLE
Preserve space within single-line code blocks

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Review by martint — APPROVED** [review]

**Comment by findepi** [comment]
i just realized the change may have a small side-effect, perhaps anticipated by some

```java
private MyClass() {}
```

may now format as

```java
private MyClass() { }
```

**Comment by martint** [comment]
That’s an acceptable tradeoff, IMO.

**Comment by findepi** [comment]
it reads perfectly, agreed.
not sure whether this violates airbase checkstyle rules though.

**Comment by findepi** [comment]
Follow-up: https://github.com/airlift/codestyle/pull/16

**Pull request merged**
