### PR TITLE
Wrap long argument lists

### PR DESCRIPTION
**Pull request by findepi**
Enable 'Chop down if long' formatting for method declarations and call
arguments.

### CODE REVIEW

**Comment by findepi** [comment]
This has a downside that the margin is enforced rather than being advisory.
There are occasions where i intentionally overrun the margin for readability.

**Review by hashhar — COMMENTED** [review]
LGTM for `CALL_PARAMETERS_LPAREN_ON_NEXT_LINE` and `METHOD_PARAMETERS_LPAREN_ON_NEXT_LINE` (assuming they control placement of braces regardless of long argument lists.

For long arguments it's a bit subjective so I'd prefer not to add it (since it's very strict).

**Comment by findepi** [comment]
> LGTM for `CALL_PARAMETERS_LPAREN_ON_NEXT_LINE` and `METHOD_PARAMETERS_LPAREN_ON_NEXT_LINE` (assuming they control placement of braces regardless of long argument lists.

Would you want to verify it?

**Comment by hashhar** [comment]
> > LGTM for `CALL_PARAMETERS_LPAREN_ON_NEXT_LINE` and `METHOD_PARAMETERS_LPAREN_ON_NEXT_LINE` (assuming they control placement of braces regardless of long argument lists.
> 
> Would you want to verify it?

Verified. They control the placement of `(` when parameters are chopped.

```diff
-    public static DistributedQueryRunner createPostgreSqlQueryRunner(TestingPostgreSqlServer server,
+    public static DistributedQueryRunner createPostgreSqlQueryRunner(
+            TestingPostgreSqlServer server,
             Map<String, String> extraProperties,
```
and
```diff
-        DistributedQueryRunner queryRunner = createPostgreSqlQueryRunner(new TestingPostgreSqlServer(),
+        DistributedQueryRunner queryRunner = createPostgreSqlQueryRunner(
+                new TestingPostgreSqlServer(),
                 ImmutableMap.of("http-server.http.port", "8080"),
```

**Comment by findepi** [comment]
@hashhar sadly it applies also for

```
assertQuery("blah blah" +
   "blah blah ");

```

**Pull request closed without merging**
